
import { writeFileSync } from 'node:fs';

const theFileName = 'importDay.ts';

function generateTheCode(): string {
    return thecode;
}

const thePreamble = `// This code was generated by \`src/scripts/codegen.ts\`. Do not modify.`;
const thecode = `${thePreamble}

export async function getDaySolution(day: number) {
    switch (day) {
        case 1: return await import("@scripts/day01");
        case 2: return await import("@scripts/day02");
    }
}
`

export default {
    name: 'codegen',
    hooks: {
        //@ts-ignore
        'astro:config:setup': ({ createCodegenDir }) => {
            const codegenDir = createCodegenDir();
            writeFileSync(new URL(theFileName, codegenDir), generateTheCode(), 'utf-8')
        }
    }
}
